bt:
  environment: sandbox
  merchant: 
    id: 5tndvhyk8sybykg8
  public: 
    key: jscw6xt34ynr42bm
  private: 
    key: 70605044876ed203a04572aa4cf4fa82

spring: 
  mvc: 
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  
  datasource: 
    druid: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://db.dev.51szzc.com:3306/szzc-wallet-dev?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8
      username: szzc_wallet
      password: szzc_wallet
      initial-size: 5
      min-idle: 5
      max-active: 30
      
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.busd.entity
  global-config: 
    # 数据库相关配置
    db-config: 
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: IGNORED
      #驼峰下划线转换
      column-underline: true
      #table-prefix: t_
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
#      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

